"""update table

Revision ID: 738369aaf18f
Revises: fe924eb33220
Create Date: 2023-08-30 12:41:38.706584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738369aaf18f'
down_revision = 'fe924eb33220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
