"""update table

Revision ID: fe924eb33220
Revises: c2d5894073fd
Create Date: 2023-08-27 14:13:44.735775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe924eb33220'
down_revision = 'c2d5894073fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
